# Generated by Django 5.2.14 on 2026-05-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(unique=True)),
                ('tax_revenue', models.PositiveIntegerField(help_text='Tax/fee amount in KES')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Loan Amount Option',
                'verbose_name_plural': 'Loan Amount Options',
                'ordering': ['order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=20)),
                ('loan_type', models.CharField(choices=[('business', 'Business Loan'), ('personal', 'Personal Loan'), ('emergency', 'Emergency Loan'), ('education', 'Education Loan')], max_length=20)),
                ('selected_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Tala Mkopo Extra', max_length=100)),
                ('tagline', models.CharField(default='Get Up To Ksh 100,000 Fast', max_length=200)),
                ('max_loan_amount', models.PositiveIntegerField(default=100000)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Interest rate in %', max_digits=5)),
                ('loan_term_months', models.PositiveIntegerField(default=2, help_text='Loan term in months')),
                ('hero_subtitle', models.CharField(default='Low 7.5% interest rate for qualified borrowers', max_length=300)),
                ('footer_text', models.CharField(default='© 2025 Tala Mkopo Extra. Licensed by CBK.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
